//! Core domain logic, shared by the native host and the WASM guest.
//!
//! This crate is the single source of truth for summarization logic so the
//! same code runs natively (tests, host fallback) and inside the sandboxed
//! WASM component. It has no I/O and no platform dependencies (PRD §12.0:
//! "WASM does bounded/streamed pure compute"; logic never lives in handlers).

mod coverage;
mod delivery;
mod failure;
mod identity;
mod job;
mod membership;
mod message;
mod rolling;
mod schedule;
mod secret;
mod session;
pub mod summarize;
mod whatsapp;
mod workspace;
pub use coverage::{analyze_coverage, CoverageGap, CoverageReport, GapKind, Span};
pub use delivery::{
    resolve as resolve_delivery, visible_kinds, DeliveryCapabilities, DeliveryDecision,
    DeliveryReject, Destination, DestinationKind,
};
pub use failure::FailureClass;
pub use identity::{
    resolve_link, DiscordProvider, EmailProvider, GoogleProvider, IdentityLink, IdentityProvider,
    LinkIntent, LinkOutcome, ProviderClaims, ProviderKind, Subject, VerifiedIdentity,
};
pub use job::{InvalidTransition, Job, JobId, JobStatus, JobType};
pub use membership::{
    evaluate_accept, AcceptOutcome, AcceptReject, Invite, InviteStatus, Membership, Permission,
    Role,
};
pub use message::{
    clean_content, extract_code_blocks, Attachment, AttachmentKind, ChannelId, CodeBlock,
    MessageId, NormalizedMessage,
};
pub use rolling::{
    decide_rolling, AccumulationStrategy, PeriodWindow, RollingAction, RollingPeriod, RollingState,
};
pub use schedule::{evaluate_tick, Schedule, ScheduleError, ScheduleType, TickAction, TimeOfDay};
pub use secret::Secret;
pub use session::{
    evaluate_refresh, AccessClaims, RefreshOutcome, RefreshReject, RefreshTokenHash, Session,
    SessionId,
};
pub use whatsapp::{
    parse_export, ChatEvent, ChatEventKind, DateOrder, ParsedExport, RawWhatsAppMessage,
    WhatsAppFormat,
};
pub use workspace::{
    Platform, PlatformId, Tenant, TenantId, UserId, Workspace, WorkspaceConnection,
};

/// Declares a validated, bounded, non-empty string id newtype. Construction via
/// `parse` is the only way in, so an existing value is guaranteed well-formed
/// (parse, don't validate). Shared by the workspace and identity models.
macro_rules! string_id {
    ($(#[$meta:meta])* $name:ident, $field:literal, $max:expr) => {
        $(#[$meta])*
        #[derive(Debug, Clone, PartialEq, Eq, Hash)]
        pub struct $name(String);

        impl $name {
            pub const MAX_LEN: usize = $max;

            pub fn parse(raw: impl Into<String>) -> Result<Self, $crate::ValidationError> {
                Ok(Self($crate::parse_id($field, raw, Self::MAX_LEN)?))
            }

            pub fn as_str(&self) -> &str {
                &self.0
            }
        }
    };
}
pub(crate) use string_id;

string_id!(
    /// Per-request trace id (PRD §12.2 item 3). Generated by the host at the
    /// edge and threaded through services, audit entries, and logs so a single
    /// request can be followed end-to-end. The domain only validates it.
    CorrelationId,
    "correlation id",
    128
);

/// Validation failures surfaced at system boundaries (PRD §12.0: fail-fast,
/// newtypes, no silent fallbacks). `field` names the offending input so the
/// same variants serve every validated newtype.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ValidationError {
    Empty {
        field: &'static str,
    },
    TooLong {
        field: &'static str,
        len: usize,
        max: usize,
    },
    Invalid {
        field: &'static str,
        reason: &'static str,
    },
}

impl std::fmt::Display for ValidationError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ValidationError::Empty { field } => write!(f, "{field} must not be empty"),
            ValidationError::TooLong { field, len, max } => {
                write!(f, "{field} length {len} exceeds max {max}")
            }
            ValidationError::Invalid { field, reason } => write!(f, "{field} is invalid: {reason}"),
        }
    }
}

impl std::error::Error for ValidationError {}

/// Shared parser for the bounded, non-empty string ids used as newtypes.
pub(crate) fn parse_id(
    field: &'static str,
    raw: impl Into<String>,
    max: usize,
) -> Result<String, ValidationError> {
    let raw = raw.into();
    if raw.trim().is_empty() {
        return Err(ValidationError::Empty { field });
    }
    if raw.len() > max {
        return Err(ValidationError::TooLong {
            field,
            len: raw.len(),
            max,
        });
    }
    Ok(raw)
}

/// A validated workspace identifier. Construction is the only way in, so an
/// existing `WorkspaceId` is guaranteed well-formed (parse, don't validate).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct WorkspaceId(String);

impl WorkspaceId {
    /// Maximum accepted length; generous but bounded to reject abuse early.
    pub const MAX_LEN: usize = 256;

    pub fn parse(raw: impl Into<String>) -> Result<Self, ValidationError> {
        Ok(Self(parse_id("workspace id", raw, Self::MAX_LEN)?))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// Bounded input to the pure-compute summarizer.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SummaryInput {
    pub workspace_id: WorkspaceId,
    pub messages: Vec<String>,
}

/// Result of summarization. `message_count`/`word_count` are derived invariants
/// the property tests pin down.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Summary {
    pub text: String,
    pub message_count: u32,
    pub word_count: u32,
}

/// Number of leading words kept in the preview line.
const PREVIEW_WORDS: usize = 12;

/// Produce a trivial extractive summary. Deterministic and side-effect free —
/// a placeholder for the real Phase 4 pipeline, sufficient to prove the
/// host -> WASM -> repository -> DB walking skeleton.
pub fn summarize(input: &SummaryInput) -> Summary {
    let message_count = input.messages.len() as u32;
    let word_count = input
        .messages
        .iter()
        .flat_map(|m| m.split_whitespace())
        .count() as u32;
    let preview: String = input
        .messages
        .first()
        .map(|m| {
            m.split_whitespace()
                .take(PREVIEW_WORDS)
                .collect::<Vec<_>>()
                .join(" ")
        })
        .unwrap_or_default();
    let text = format!("[{message_count} msgs / {word_count} words] {preview}");
    Summary {
        text,
        message_count,
        word_count,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    #[test]
    fn workspace_id_rejects_empty_and_blank() {
        assert!(matches!(
            WorkspaceId::parse(""),
            Err(ValidationError::Empty { .. })
        ));
        assert!(matches!(
            WorkspaceId::parse("   "),
            Err(ValidationError::Empty { .. })
        ));
    }

    #[test]
    fn workspace_id_rejects_overlong() {
        let raw = "x".repeat(WorkspaceId::MAX_LEN + 1);
        assert!(matches!(
            WorkspaceId::parse(raw),
            Err(ValidationError::TooLong { .. })
        ));
    }

    #[test]
    fn summarize_empty_is_zeroed() {
        let input = SummaryInput {
            workspace_id: WorkspaceId::parse("ws").unwrap(),
            messages: vec![],
        };
        let s = summarize(&input);
        assert_eq!(s.message_count, 0);
        assert_eq!(s.word_count, 0);
    }

    proptest! {
        // message_count always equals the number of input messages.
        #[test]
        fn message_count_matches_input(msgs in proptest::collection::vec(".*", 0..50)) {
            let input = SummaryInput {
                workspace_id: WorkspaceId::parse("ws").unwrap(),
                messages: msgs.clone(),
            };
            prop_assert_eq!(summarize(&input).message_count as usize, msgs.len());
        }

        // word_count equals the total whitespace-split token count.
        #[test]
        fn word_count_matches_tokens(msgs in proptest::collection::vec("[a-z ]{0,40}", 0..50)) {
            let expected: usize = msgs.iter().flat_map(|m| m.split_whitespace()).count();
            let input = SummaryInput {
                workspace_id: WorkspaceId::parse("ws").unwrap(),
                messages: msgs,
            };
            prop_assert_eq!(summarize(&input).word_count as usize, expected);
        }

        // summarize is pure: identical input yields identical output.
        #[test]
        fn summarize_is_deterministic(msgs in proptest::collection::vec(".*", 0..30)) {
            let input = SummaryInput {
                workspace_id: WorkspaceId::parse("ws").unwrap(),
                messages: msgs,
            };
            prop_assert_eq!(summarize(&input), summarize(&input));
        }
    }
}
